const RESTAURANT_OWNER_TABLE_NAME = "RestaurantOwner";
const RESTAURANT_OWNER_FIRST_NAME = "first_name";
const RESTAURANT_OWNER_LAST_NAME = "last_name";
const RESTAURANT_OWNER_EMAIL = "email";
const RESTAURANT_OWNER_PASSWORD = "password";

const RESTAURANT_OWNER_TABLE_CREATION_SQL = `
CREATE TABLE IF NOT EXISTS ${RESTAURANT_OWNER_TABLE_NAME} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ${RESTAURANT_OWNER_FIRST_NAME} TEXT NOT NULL,
    ${RESTAURANT_OWNER_LAST_NAME} TEXT NOT NULL,
    ${RESTAURANT_OWNER_EMAIL} TEXT UNIQUE NOT NULL,
    ${RESTAURANT_OWNER_PASSWORD} TEXT NOT NULL
)
`

const RESTAURANT_OWNER_REGISTRATION_DETAILS = [RESTAURANT_OWNER_EMAIL, RESTAURANT_OWNER_FIRST_NAME, RESTAURANT_OWNER_LAST_NAME, RESTAURANT_OWNER_PASSWORD];
const RESTAURANT_OWNER_FROM_SESSION_DETAILS = [RESTAURANT_OWNER_EMAIL];

module.exports = {
    RESTAURANT_OWNER_TABLE_CREATION_SQL,
    RESTAURANT_OWNER_TABLE_NAME,
    RESTAURANT_OWNER_EMAIL,
    RESTAURANT_OWNER_REGISTRATION_DETAILS,
    RESTAURANT_OWNER_FROM_SESSION_DETAILS,
    RESTAURANT_OWNER_FIRST_NAME,
    RESTAURANT_OWNER_LAST_NAME,
    RESTAURANT_OWNER_PASSWORD
}