const path = require("path");
const { RESTAURANT_OWNER_TABLE_NAME, RESTAURANT_OWNER_EMAIL } = require(path.join(__dirname, "restaurantOwnerConstants"));

const RESTAURANT_DB_TABLE_NAME = "Restaurant";
const RESTAURANT_NAME = "restaurant_name";
const RESTAURANT_DESCRIPTION = "restaurant_description";
const RESTAURANT_DB_OWNER_EMAIL = "restaurant_owner_email";
const RESTAURANT_COVER_IMAGE = "restaurant_cover_image";

const RESTAURANT_DB_CREATION_SQL = `
CREATE TABLE IF NOT EXISTS ${RESTAURANT_DB_TABLE_NAME} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ${RESTAURANT_NAME} TEXT NOT NULL,
    ${RESTAURANT_DESCRIPTION} TEXT,
    ${RESTAURANT_DB_OWNER_EMAIL} TEXT NOT NULL,
    ${RESTAURANT_COVER_IMAGE} BLOB,
    FOREIGN KEY (${RESTAURANT_DB_OWNER_EMAIL}) REFERENCES ${RESTAURANT_OWNER_TABLE_NAME}(${RESTAURANT_OWNER_EMAIL})
);
`

module.exports = {
    RESTAURANT_DB_CREATION_SQL,
    RESTAURANT_NAME,
    RESTAURANT_DB_TABLE_NAME,
    RESTAURANT_DESCRIPTION,
    RESTAURANT_DB_OWNER_EMAIL,
    RESTAURANT_COVER_IMAGE
};