const USER_FIRST_NAME = "first_name";
const USER_LAST_NAME = "last_name";
const USER_EMAIL = "email";
const USER_PASSWORD = "password";

const USER_TABLE_NAME = "User"

const USER_DB_TABLE_CREATION_SQL = `
CREATE TABLE IF NOT EXISTS ${USER_TABLE_NAME} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ${USER_FIRST_NAME} TEXT NOT NULL,
    ${USER_LAST_NAME} TEXT NOT NULL,
    ${USER_EMAIL} TEXT UNIQUE NOT NULL,
    ${USER_PASSWORD} TEXT NOT NULL
)
`

const USER_REGESTERATION_DETAILS = [USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_PASSWORD];

const USER_INFORMATION_FROM_SESSION_DETAILS = [USER_EMAIL];
const USER_LOGIN_DETAILS = [USER_EMAIL, USER_PASSWORD];

module.exports = {
    USER_FIRST_NAME,
    USER_LAST_NAME,
    USER_EMAIL,
    USER_PASSWORD,
    USER_TABLE_NAME,
    USER_DB_TABLE_CREATION_SQL,
    USER_REGESTERATION_DETAILS,
    USER_LOGIN_DETAILS,
    USER_INFORMATION_FROM_SESSION_DETAILS
};